"""added user_id to invoice model

Revision ID: 2dd02805c140
Revises: b457e63472ec
Create Date: 2026-03-05 17:18:32.417589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dd02805c140'
down_revision: Union[str, Sequence[str], None] = 'b457e63472ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ✅ 1. Сначала создаём ENUM тип
    op.execute("CREATE TYPE userrole AS ENUM ('user', 'admin')")
    
    # ✅ 2. Теперь можно добавлять колонку с этим типом
    op.add_column('invoices', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_invoices_user_id'), 'invoices', ['user_id'], unique=False)
    op.create_foreign_key(op.f('fk_invoices_user_id_users'), 'invoices', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    
    op.add_column('users', sa.Column('role', sa.Enum('user', 'admin', name='userrole'), nullable=False))
    op.drop_column('users', 'is_superuser')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ✅ В downgrade удаляем ENUM в конце (после удаления колонок)
    op.add_column('users', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'role')
    op.drop_constraint(op.f('fk_invoices_user_id_users'), 'invoices', table_name='invoices', type_='foreignkey')
    op.drop_index(op.f('ix_invoices_user_id'), table_name='invoices')
    op.drop_column('invoices', 'user_id')
    
    # ✅ Удаляем ENUM тип
    op.execute("DROP TYPE IF EXISTS userrole")
    # ### end Alembic commands ###