"""replace plan price with plan_prices and add subscription currency

Revision ID: ba60438414f7
Revises: 15eae08f6090
Create Date: 2026-06-12 18:55:38.866728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba60438414f7'
down_revision: Union[str, Sequence[str], None] = '15eae08f6090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_plan_prices_plan_id_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_prices')),
    sa.UniqueConstraint('plan_id', 'currency', name='uq_plan_prices_plan_id_currency')
    )
    op.create_index(op.f('ix_plan_prices_plan_id'), 'plan_prices', ['plan_id'], unique=False)
    op.drop_column('plans', 'currency')
    op.drop_column('plans', 'price')
    op.add_column(
        'subscriptions',
        sa.Column('currency', sa.String(length=10), nullable=False, server_default='USD'),
    )
    op.alter_column('subscriptions', 'currency', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'currency')
    op.add_column('plans', sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False, server_default='0'))
    op.add_column('plans', sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=False, server_default='USD'))
    op.drop_index(op.f('ix_plan_prices_plan_id'), table_name='plan_prices')
    op.drop_table('plan_prices')
    # ### end Alembic commands ###
