"""add_incomplete_to_subscription_status

Revision ID: d937ce54e71b
Revises: 2dd02805c140
Create Date: 2026-03-13 16:36:53.466615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd937ce54e71b'
down_revision: Union[str, Sequence[str], None] = '2dd02805c140'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_api_usage_user_period', 'api_usage', ['user_id', 'period_start', 'period_end'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_api_usage_user_period', table_name='api_usage')
    # ### end Alembic commands ###
