"""add_incomplete_subscription_status

Revision ID: e65b250a8751
Revises: d937ce54e71b
Create Date: 2026-03-13 16:49:28.630848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e65b250a8751'
down_revision: Union[str, Sequence[str], None] = 'd937ce54e71b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("COMMIT")
    
    # subscriptionstatus
    op.execute("ALTER TYPE subscriptionstatus ADD VALUE IF NOT EXISTS 'incomplete'")
    
    # paymentprovider
    op.execute("ALTER TYPE paymentprovider ADD VALUE IF NOT EXISTS 'yookassa'")
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
