"""add canceled_at to subscriptions

Revision ID: e819e4ec0d78
Revises: 09055a44faf5
Create Date: 2026-03-05 08:38:22.573347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e819e4ec0d78'
down_revision: Union[str, Sequence[str], None] = '09055a44faf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('canceled_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'canceled_at')
    # ### end Alembic commands ###
